mod app_repo;
mod test_repo;
mod recording_repo;
mod issue_repo;
mod checklist_repo;
mod screenshot_repo;
mod tag_repo;
mod settings_repo;
mod document_repo;
mod diagram_repo;
mod architecture_doc_repo;
mod demo_repo;

pub use app_repo::AppRepository;
pub use test_repo::TestRepository;
pub use recording_repo::RecordingRepository;
pub use issue_repo::IssueRepository;
pub use checklist_repo::ChecklistRepository;
pub use screenshot_repo::ScreenshotRepository;
pub use tag_repo::TagRepository;
pub use settings_repo::SettingsRepository;
pub use document_repo::DocumentRepository;
pub use diagram_repo::DiagramRepository;
pub use architecture_doc_repo::ArchitectureDocRepository;
pub use demo_repo::DemoRepository;
